spring:
  application:
    name: kafkamsp
  datasource:
    dynamic:
      primary: ds-master
      hikari:
        connection-timeout: 30000
        validation-timeout: 5000
        idle-timeout: 600000
        leak-detection-threshold: 0
        max-lifetime: 1800000
        max-pool-size: 10
        min-idle: 10
        initialization-fail-timeout: 1
        is-auto-commit: false
        is-read-only: false
        is-isolate-internal-queries: false
        is-register-mbeans: false
        is-allow-pool-suspension: false
      datasource:
        ds-master:
          hikari:
            is-auto-commit: false
          driver-class-name: org.h2.Driver
          url: jdbc:h2:~/h2/ds-master;DATABASE_TO_LOWER=TRUE;
          username: sa
          password: sa
  cloud:
    stream:
      function:
        #配置消费者消费的方法名称，按bindings顺序，多个以英文分号隔开
        definition: producer
      bindings:
#        #生产者
        producer-out-0:
          #主题名称
          destination: KAFKA_TEST_TOPIC

kudos:
  ability:
    distributed:
      stream:
        save-exception: true
    flyway:
      datasource-config:
        mq: ds-master

server:
  port: 53322


#logging:
#  level:
#    root: DEBUG
