spring:
  cloud:
    stream:
      function:
        #配置消费者消费的方法名称，按bindings顺序，多个以英文分号隔开
        definition: consumer
      bindings:
        consumer-in-0:
          destination: ROCKETMQ_TEST_TOPIC
          content-type: application/json
          group: unitTest
          consumer:
            concurrency: 5

  datasource:
    dynamic:
      primary: postgres
      hikari:
        connection-timeout: 30000
        validation-timeout: 5000
        idle-timeout: 600000
        leak-detection-threshold: 0
        max-lifetime: 1800000
        max-pool-size: 10
        min-idle: 10
        initialization-fail-timeout: 1
        is-auto-commit: false
        is-read-only: false
        is-isolate-internal-queries: false
        is-register-mbeans: false
        is-allow-pool-suspension: false
      datasource:
        postgres:
          hikari:
            is-auto-commit: false
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/test
          username: pg
          password: postgres

