spring:
  datasource:
    dynamic:
      primary: ds1
      hikari:
        connection-timeout: 30000
        validation-timeout: 5000
        idle-timeout: 600000
        leak-detection-threshold: 0
        max-lifetime: 1800000
        max-pool-size: 10
        min-idle: 10
        initialization-fail-timeout: 1
        is-auto-commit: false
        is-read-only: false
        is-isolate-internal-queries: false
        is-register-mbeans: false
        is-allow-pool-suspension: false
      datasource:
        ds1:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:~/h2/ds1;DATABASE_TO_LOWER=TRUE;
          username: sa
          password: sa
          init:
            schema: sql/schema.sql
            data: sql/data.sql