kudos:
  ability:
    distributed:
      stream:
        save-exception: true

spring:
  flyway:
    locations:
      - classpath:db/stream/postgresql

soul:
  ability:
    distributed:
      stream:
        save-exception: ${kudos.ability.distributed.stream.save-exception}

