kudos:
  ability:
    distributed:
      stream:
        save-exception: true
    flyway:
      datasource-config:
        mq: postgres
spring:
  flyway:
    locations:
      - classpath:db/stream/postgresql




