spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:28848
        namespace: public
        file-extension: yml
  config:
    import:
      - optional:nacos:test.yml
#      - optional:nacos:test.yml  # 监听 DEFAULT_GROUP:test.yml
#      - optional:nacos:test01.yml?group=group_01 # 覆盖默认 group，监听 group_01:test01.yml
#      - optional:nacos:test02.yml?group=group_02&refreshEnabled=false # 不开启动态刷新
#      - nacos:test03.yml # 在拉取nacos配置异常时会快速失败，会导致 spring 容器启动失败
  application:
    name: example