server:
  port: 0

spring:
  application:
    name: discovery
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:28848
        register-enabled: true         # 确保开启自动注册
        ip: 127.0.0.1                  # 指定注册到 Nacos 的 IP


#logging:
#  level:
#    root: DEBUG
#    com.alibaba.cloud: DEBUG